; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

lib_deps =
    bodmer/TFT_eSPI

build_flags =
    -D USER_SETUP_LOADED
    -D ST7789_DRIVER
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=D10
    -D TFT_SCLK=D8
    -D TFT_CS=D0
    -D TFT_DC=D2
    -D TFT_RST=D1
    -D LOAD_GLCD
    -D SPI_FREQUENCY=40000000

upload_port = COM10
monitor_port = COM10
monitor_speed = 115200