; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

lib_deps =
    bodmer/TFT_eSPI
build_flags =
    -D USER_SETUP_LOADED
    -D ST7789_DRIVER
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=9
    -D TFT_SCLK=7
    -D TFT_CS=1
    -D TFT_DC=3
    -D TFT_RST=2
    -D USE_HSPI_PORT
    -D LOAD_GLCD
    -D SPI_FREQUENCY=10000000

upload_speed = 115200
monitor_speed = 115200